In [2]:
import  pandas
import yfinance

raw = yfinance.download(["CL=F","GC=F","^GSPC"],start= "2025-01-01",end= "2026-06-10")
raw.head(10)

[*********************100%***********************]  3 of 3 completed

Price           Close                                 High               \
Ticker           CL=F         GC=F        ^GSPC       CL=F         GC=F
Date
2025-01-02  73.129997  2658.899902  5868.549805  73.730003  2663.100098
2025-01-03  73.959999  2645.000000  5942.470215  74.349998  2658.699951
2025-01-06  73.559998  2638.399902  5975.379883  74.989998  2647.000000
2025-01-07  74.250000  2656.699951  5909.029785  74.529999  2657.500000
2025-01-08  73.320000  2664.500000  5918.250000  75.290001  2676.899902
2025-01-09  73.919998  2683.800049          NaN  74.320000  2686.300049
2025-01-10  76.570000  2708.500000  5827.040039  77.860001  2720.100098
2025-01-13  78.820000  2673.500000  5836.220215  79.269997  2711.199951
2025-01-14  77.500000  2677.500000  5842.910156  79.089996  2688.300049
2025-01-15  80.040001  2712.500000  5949.910156  80.769997  2712.500000

Price                          Low                                 Open  \
Ticker            ^GSPC       CL=F         GC=F        ^GSPC       CL=F
Date
2025-01-02  5935.089844  71.790001  2633.000000  5829.529785  71.849998
2025-01-03  5949.339844  72.699997  2641.800049  5888.660156  73.129997
2025-01-06  6021.040039  73.199997  2617.300049  5960.009766  74.050003
2025-01-07  6000.680176  73.110001  2653.000000  5890.680176  73.440002
2025-01-08  5927.890137  73.160004  2653.500000  5874.779785  74.519997
2025-01-09          NaN  72.839996  2667.899902          NaN  73.320000
2025-01-10  5890.350098  74.019997  2683.699951  5807.779785  74.290001
2025-01-13  5838.609863  76.540001  2673.500000  5773.310059  76.540001
2025-01-14  5871.919922  77.410004  2670.800049  5805.419922  78.820000
2025-01-15  5960.609863  77.239998  2690.800049  5905.209961  78.029999

Price                                 Volume
Ticker             GC=F        ^GSPC    CL=F  GC=F         ^GSPC
Date
2025-01-02  2633.000000  5903.259766  306498  1728  3.621680e+09
2025-01-03  2658.699951  5891.069824  296040   591  3.667340e+09
2025-01-06  2645.500000  5982.810059  306042   960  4.940120e+09
2025-01-07  2653.399902  5993.259766  277328   643  4.517330e+09
2025-01-08  2655.500000  5910.660156  328617   999  4.441740e+09
2025-01-09  2669.699951          NaN  213421  1139           NaN
2025-01-10  2686.100098  5890.350098  478432   403  4.751930e+09
2025-01-13  2711.100098  5782.020020  460942   765  4.421200e+09
2025-01-14  2673.600098  5859.270020  326729   794  4.142280e+09
2025-01-15  2690.800049  5905.209961  321422   930  4.544570e+09

In [3]:
print(raw['Close'].head())

Ticker           CL=F         GC=F        ^GSPC
Date
2025-01-02  73.129997  2658.899902  5868.549805
2025-01-03  73.959999  2645.000000  5942.470215
2025-01-06  73.559998  2638.399902  5975.379883
2025-01-07  74.250000  2656.699951  5909.029785
2025-01-08  73.320000  2664.500000  5918.250000

In [4]:
print(raw.shape)
print(raw.columns)

(361, 15)
MultiIndex([( 'Close',  'CL=F'),
            ( 'Close',  'GC=F'),
            ( 'Close', '^GSPC'),
            (  'High',  'CL=F'),
            (  'High',  'GC=F'),
            (  'High', '^GSPC'),
            (   'Low',  'CL=F'),
            (   'Low',  'GC=F'),
            (   'Low', '^GSPC'),
            (  'Open',  'CL=F'),
            (  'Open',  'GC=F'),
            (  'Open', '^GSPC'),
            ('Volume',  'CL=F'),
            ('Volume',  'GC=F'),
            ('Volume', '^GSPC')],
           names=['Price', 'Ticker'])

In [9]:
close=raw['Volume']
close.head()
normalized = (close / close.iloc[0]) * 100
normalized.head()

Ticker            CL=F        GC=F       ^GSPC
Date
2025-01-02  100.000000  100.000000  100.000000
2025-01-03   96.587906   34.201389  101.260741
2025-01-06   99.851223   55.555556  136.404100
2025-01-07   90.482809   37.210648  124.730236
2025-01-08  107.216687   57.812500  122.643083

In [46]:
import plotly.express as px
close=raw['Close']
normalized = (close / close.iloc[0]) * 100
normalized.columns=['Crude oil','Gold','S&P 500 index']
fig = px.line(
    normalized,
    title="WarPower — US-Iran War 2026: Resource Impact"
 )

normalized.columns=['oil','gold','stocks']
normalized.head()
fig.add_vline(x='2026-02-28', line_width=2, line_dash="dash", line_color="red",annotation_text="US-Iran War Begins", annotation_position="top left")
fig.add_vline(x='2026-04-08', line_width=2, line_dash="dash", line_color="Green",annotation_text="Ceasefire Declared", annotation_position="top right")
fig.show(renderer="browser")

In [43]:
normalized = (close / close.iloc[0]) * 100
normalized.head()

Ticker            CL=F        GC=F       ^GSPC
Date
2025-01-02  100.000000  100.000000  100.000000
2025-01-03  101.134968   99.477231  101.259603
2025-01-06  100.587994   99.229004  101.820383
2025-01-07  101.531523   99.917261  100.689778
2025-01-08  100.259815  100.210617  100.846891

In [40]:
import plotly.express as px
import pandas as pd
import yfinance
raw2 = yfinance.download(['NG=F','ZW=F','LMT','JPY=X'],start="2025-01-01", end="2026-06-10")
close2=raw2['Close']
normalized2 = (close2 / close2.iloc[0]) * 100
normalized2.columns = ['USD/JPY', 'Lockheed Martin', 'Natural Gas', 'Wheat']
normalized2.loc['2026-01-28', 'Natural Gas'] = None
normalized2['Natural Gas'] = normalized2['Natural Gas'].ffill()
fig2=px.line(
    normalized2,
    title="WarPower — US-Iran War 2026: Resource Impact (Energy, Food, Defense, Currency)"
)
fig2.add_vline(x='2026-02-28', line_width=2, line_dash="dash", line_color="red",annotation_text="US-Iran War Begins", annotation_position="top left")
fig2.add_vline(x='2026-04-08', line_width=2, line_dash="dash", line_color="Green",annotation_text="Ceasefire Declared", annotation_position="top right")
fig2.show()

[*********************100%***********************]  4 of 4 completed

In [37]:
import pandas as pd
peak_date = normalized2['Natural Gas'].idxmax()
print(normalized2['Natural Gas'].loc[peak_date - pd.Timedelta(days=5) : peak_date + pd.Timedelta(days=5)])

Date
2026-01-23    144.125682
2026-01-26    185.792351
2026-01-27    189.999995
2026-01-28    203.825133
2026-01-29    107.049177
2026-01-30    118.961748
2026-02-02     88.442621
Name: Natural Gas, dtype: float64

In [54]:
all_data= pd.concat([normalized,normalized2],axis=1,sort=False)
before= all_data.loc['2026-02-27']
after= all_data.loc['2026-03-30']
pct_change = ((after - before) / before) * 100
print(pct_change)

oil                53.506420
gold              -13.469076
stocks             -7.779750
USD/JPY             2.807024
Lockheed Martin    -8.563614
Natural Gas         0.979367
Wheat               2.663848
dtype: float64